export const categories = [
  // ======================
  // TECHNOLOGY & COMPUTING
  // ======================
  {
    name: "Technology & Computing",
    subcategories: [
      {
        name: "Computer Science Specializations",
        segments: [
          { name: "Artificial Intelligence (AI)" },
          { name: "Machine Learning (ML)" },
          { name: "Deep Learning" },
          { name: "Natural Language Processing (NLP)" },
          { name: "Data Science" },
          { name: "Computer Vision" },
          { name: "Cybersecurity" },
          { name: "Cloud Computing" },
          { name: "High Performance Computing" },
          { name: "Quantum Computing" },
          { name: "Computer Communication Engineering (CCE)" },
          { name: "Big Data Engineering" },
          { name: "Blockchain" },
          { name: "Internet of Things (IoT)" },
          { name: "Augmented Reality (AR)" },
          { name: "Virtual Reality (VR)" },
          { name: "Game Development" },
          { name: "Computer Graphics" },
          { name: "Robotics" },
          { name: "Distributed Systems" },
          { name: "Database Systems" },
          { name: "Information Security" },
          { name: "Human-Computer Interaction (HCI)" },
          { name: "Software Engineering" },
          { name: "Algorithm Design" },
          { name: "Bioinformatics" },
          { name: "Computational Biology" },
          { name: "Digital Forensics" },
          { name: "Embedded Systems" },
          { name: "Real-time Systems" },
        ],
      },
      {
        name: "Web Development",
        segments: [
          { name: "Frontend Development" },
          { name: "React.js" },
          { name: "Vue.js" },
          { name: "Angular" },
          { name: "JavaScript" },
          { name: "TypeScript" },
          { name: "HTML/CSS" },
          { name: "SASS/SCSS" },
          { name: "Bootstrap" },
          { name: "Tailwind CSS" },
          { name: "jQuery" },
          { name: "Progressive Web Apps (PWA)" },
          { name: "Single Page Applications (SPA)" },
          { name: "Responsive Design" },
          { name: "Web Accessibility" },
          { name: "Web Performance Optimization" },
          { name: "SEO Optimization" },
          { name: "Cross-browser Compatibility" },
        ],
      },
      {
        name: "Backend Development",
        segments: [
          { name: "Node.js" },
          { name: "Python (Django/Flask)" },
          { name: "Java (Spring Boot)" },
          { name: "C# (.NET)" },
          { name: "PHP (Laravel/Symfony)" },
          { name: "Ruby on Rails" },
          { name: "Go (Golang)" },
          { name: "Rust" },
          { name: "Scala" },
          { name: "API Development" },
          { name: "REST APIs" },
          { name: "GraphQL" },
          { name: "Microservices" },
          { name: "Serverless Computing" },
          { name: "Database Design" },
          { name: "SQL" },
          { name: "NoSQL" },
          { name: "Redis" },
          { name: "Message Queues" },
          { name: "Caching Strategies" },
        ],
      },
      {
        name: "Mobile Development",
        segments: [
          { name: "iOS Development (Swift)" },
          { name: "Android Development (Kotlin/Java)" },
          { name: "React Native" },
          { name: "Flutter" },
          { name: "Xamarin" },
          { name: "Ionic" },
          { name: "PhoneGap/Cordova" },
          { name: "Progressive Web Apps (PWA)" },
          { name: "Mobile UI/UX Design" },
          { name: "Mobile App Security" },
          { name: "App Store Optimization (ASO)" },
          { name: "Mobile Testing" },
          { name: "Wearable App Development" },
          { name: "Augmented Reality Mobile Apps" },
        ],
      },
      {
        name: "DevOps & Infrastructure",
        segments: [
          { name: "DevOps Engineering" },
          { name: "Site Reliability Engineering (SRE)" },
          { name: "CI/CD Pipelines" },
          { name: "Docker" },
          { name: "Kubernetes" },
          { name: "AWS" },
          { name: "Azure" },
          { name: "Google Cloud Platform (GCP)" },
          { name: "Terraform" },
          { name: "Ansible" },
          { name: "Jenkins" },
          { name: "GitLab CI" },
          { name: "Monitoring & Logging" },
          { name: "Infrastructure as Code (IaC)" },
          { name: "Container Orchestration" },
          { name: "Service Mesh" },
          { name: "Load Balancing" },
          { name: "Auto-scaling" },
        ],
      },
      {
        name: "Data Engineering & Analytics",
        segments: [
          { name: "Data Engineering" },
          { name: "ETL/ELT Processes" },
          { name: "Data Warehousing" },
          { name: "Data Lakes" },
          { name: "Apache Spark" },
          { name: "Apache Kafka" },
          { name: "Hadoop" },
          { name: "Snowflake" },
          { name: "BigQuery" },
          { name: "Redshift" },
          { name: "Data Modeling" },
          { name: "Data Visualization" },
          { name: "Business Intelligence" },
          { name: "Tableau" },
          { name: "Power BI" },
          { name: "Looker" },
          { name: "Statistical Analysis" },
          { name: "Data Mining" },
          { name: "Predictive Analytics" },
        ],
      },
      {
        name: "Quality Assurance & Testing",
        segments: [
          { name: "Manual Testing" },
          { name: "Automation Testing" },
          { name: "Selenium" },
          { name: "Cypress" },
          { name: "Jest" },
          { name: "Unit Testing" },
          { name: "Integration Testing" },
          { name: "Performance Testing" },
          { name: "Security Testing" },
          { name: "Load Testing" },
          { name: "API Testing" },
          { name: "Mobile Testing" },
          { name: "Test-Driven Development (TDD)" },
          { name: "Behavior-Driven Development (BDD)" },
          { name: "Quality Assurance Processes" },
        ],
      },
      {
        name: "Emerging Technologies",
        segments: [
          { name: "Web3 Development" },
          { name: "Smart Contracts" },
          { name: "DeFi (Decentralized Finance)" },
          { name: "NFT Development" },
          { name: "Metaverse Development" },
          { name: "Edge AI" },
          { name: "5G Technology" },
          { name: "Quantum Programming" },
          { name: "Neuromorphic Computing" },
          { name: "Brain-Computer Interfaces" },
          { name: "Autonomous Systems" },
          { name: "Digital Twins" },
          { name: "Extended Reality (XR)" },
          { name: "Computer-Generated Imagery (CGI)" },
        ],
      },
    ],
  },

  // ======================
  // EDUCATION & ACADEMICS
  // ======================
  {
    name: "Education & Academics",
    subcategories: [
      {
        name: "Engineering",
        segments: [
          { name: "Computer Science & Engineering (CSE)" },
          { name: "Electronics & Communication Engineering (ECE)" },
          { name: "Electrical Engineering (EE)" },
          { name: "Mechanical Engineering (ME)" },
          { name: "Civil Engineering" },
          { name: "Chemical Engineering" },
          { name: "Aerospace Engineering" },
          { name: "Biotechnology" },
          { name: "Robotics Engineering" },
          { name: "Automobile Engineering" },
          { name: "Industrial Engineering" },
          { name: "Materials Science Engineering" },
          { name: "Environmental Engineering" },
          { name: "Nuclear Engineering" },
          { name: "Petroleum Engineering" },
          { name: "Mining Engineering" },
          { name: "Agricultural Engineering" },
          { name: "Food Technology" },
          { name: "Textile Engineering" },
          { name: "Marine Engineering" },
          { name: "Instrumentation Engineering" },
          { name: "Biomedical Engineering" },
          { name: "Metallurgical Engineering" },
          { name: "Production Engineering" },
          { name: "Systems Engineering" },
          { name: "Software Engineering" },
          { name: "Information Technology" },
          { name: "Nanotechnology" },
          { name: "Renewable Energy Engineering" },
          { name: "Structural Engineering" },
        ],
      },
      {
        name: "Medical & Healthcare",
        segments: [
          { name: "MBBS" },
          { name: "BDS (Dental)" },
          { name: "BAMS (Ayurveda)" },
          { name: "BHMS (Homeopathy)" },
          { name: "BUMS (Unani)" },
          { name: "Nursing (B.Sc/GNM)" },
          { name: "Pharmacy (B.Pharm/D.Pharm)" },
          { name: "Physiotherapy (BPT)" },
          { name: "Occupational Therapy" },
          { name: "Medical Laboratory Technology" },
          { name: "Radiology Technology" },
          { name: "Optometry" },
          { name: "Audiology & Speech Therapy" },
          { name: "Nutrition & Dietetics" },
          { name: "Public Health" },
          { name: "Hospital Administration" },
          { name: "Medical Imaging Technology" },
          { name: "Anesthesia Technology" },
          { name: "Operation Theatre Technology" },
          { name: "Perfusion Technology" },
          { name: "Prosthetics & Orthotics" },
          { name: "Medical Biotechnology" },
          { name: "Clinical Psychology" },
          { name: "Health Informatics" },
          { name: "Veterinary Science" },
        ],
      },
      {
        name: "Pure Sciences",
        segments: [
          { name: "Physics" },
          { name: "Chemistry" },
          { name: "Mathematics" },
          { name: "Biology/Life Sciences" },
          { name: "Botany" },
          { name: "Zoology" },
          { name: "Microbiology" },
          { name: "Biochemistry" },
          { name: "Genetics" },
          { name: "Environmental Science" },
          { name: "Astronomy & Astrophysics" },
          { name: "Geology" },
          { name: "Geography" },
          { name: "Statistics" },
          { name: "Actuarial Science" },
          { name: "Forensic Science" },
          { name: "Marine Science" },
          { name: "Atmospheric Science" },
          { name: "Biophysics" },
          { name: "Materials Science" },
          { name: "Applied Mathematics" },
          { name: "Computer Science" },
          { name: "Information Science" },
          { name: "Data Science" },
          { name: "Cognitive Science" },
        ],
      },
      {
        name: "Humanities & Social Sciences",
        segments: [
          { name: "History" },
          { name: "Political Science" },
          { name: "Sociology" },
          { name: "Psychology" },
          { name: "Philosophy" },
          { name: "Economics" },
          { name: "Linguistics" },
          { name: "English Literature" },
          { name: "Hindi Literature" },
          { name: "Regional Languages" },
          { name: "Anthropology" },
          { name: "Archaeology" },
          { name: "International Relations" },
          { name: "Public Administration" },
          { name: "Social Work" },
          { name: "Gender Studies" },
          { name: "Cultural Studies" },
          { name: "Religious Studies" },
          { name: "Library Science" },
          { name: "Museum Studies" },
          { name: "Journalism" },
          { name: "Mass Communication" },
          { name: "Development Studies" },
          { name: "Peace Studies" },
          { name: "Area Studies" },
        ],
      },
      {
        name: "Law & Legal Studies",
        segments: [
          { name: "Constitutional Law" },
          { name: "Corporate Law" },
          { name: "Criminal Law" },
          { name: "Civil Law" },
          { name: "International Law" },
          { name: "Intellectual Property Law" },
          { name: "Environmental Law" },
          { name: "Labor Law" },
          { name: "Tax Law" },
          { name: "Banking Law" },
          { name: "Insurance Law" },
          { name: "Family Law" },
          { name: "Human Rights Law" },
          { name: "Cyber Law" },
          { name: "Aviation Law" },
          { name: "Maritime Law" },
          { name: "Competition Law" },
          { name: "Securities Law" },
          { name: "Real Estate Law" },
          { name: "Legal Research" },
          { name: "Jurisprudence" },
          { name: "Legal Aid" },
          { name: "Alternative Dispute Resolution" },
        ],
      },
      {
        name: "Education & Teaching",
        segments: [
          { name: "Early Childhood Education" },
          { name: "Primary Education (B.El.Ed)" },
          { name: "Secondary Education (B.Ed)" },
          { name: "Special Education" },
          { name: "Physical Education" },
          { name: "Educational Technology" },
          { name: "Educational Psychology" },
          { name: "Curriculum Development" },
          { name: "Adult Education" },
          { name: "Distance Education" },
          { name: "Educational Administration" },
          { name: "School Counseling" },
          { name: "Educational Research" },
          { name: "Instructional Design" },
          { name: "E-learning Development" },
          { name: "Academic Writing" },
          { name: "Language Teaching" },
          { name: "TESOL/TEFL" },
          { name: "Educational Assessment" },
          { name: "Inclusive Education" },
        ],
      },
      {
        name: "Agriculture & Life Sciences",
        segments: [
          { name: "Agriculture" },
          { name: "Horticulture" },
          { name: "Forestry" },
          { name: "Fisheries" },
          { name: "Animal Husbandry" },
          { name: "Dairy Science" },
          { name: "Poultry Science" },
          { name: "Soil Science" },
          { name: "Plant Pathology" },
          { name: "Entomology" },
          { name: "Agricultural Economics" },
          { name: "Agricultural Engineering" },
          { name: "Food Science & Technology" },
          { name: "Seed Technology" },
          { name: "Organic Farming" },
          { name: "Sustainable Agriculture" },
          { name: "Precision Agriculture" },
          { name: "Aquaculture" },
          { name: "Sericulture" },
          { name: "Apiculture" },
        ],
      },
    ],
  },

  // ======================
  // BUSINESS & FINANCE
  // ======================
  {
    name: "Business & Finance",
    subcategories: [
      {
        name: "Business Administration",
        segments: [
          { name: "General Management" },
          { name: "Strategic Management" },
          { name: "Operations Management" },
          { name: "Supply Chain Management" },
          { name: "Project Management" },
          { name: "Change Management" },
          { name: "Risk Management" },
          { name: "Business Process Optimization" },
          { name: "Lean Management" },
          { name: "Six Sigma" },
          { name: "Agile Management" },
          { name: "International Business" },
          { name: "Business Development" },
          { name: "Corporate Strategy" },
          { name: "Mergers & Acquisitions" },
          { name: "Business Analytics" },
          { name: "Business Intelligence" },
          { name: "Innovation Management" },
          { name: "Organizational Behavior" },
          { name: "Leadership Development" },
        ],
      },
      {
        name: "Marketing & Sales",
        segments: [
          { name: "Digital Marketing" },
          { name: "Content Marketing" },
          { name: "Social Media Marketing" },
          { name: "Search Engine Optimization (SEO)" },
          { name: "Pay-Per-Click (PPC) Advertising" },
          { name: "Email Marketing" },
          { name: "Influencer Marketing" },
          { name: "Affiliate Marketing" },
          { name: "Marketing Analytics" },
          { name: "Brand Management" },
          { name: "Product Marketing" },
          { name: "Market Research" },
          { name: "Customer Relationship Management (CRM)" },
          { name: "Sales Management" },
          { name: "B2B Sales" },
          { name: "B2C Sales" },
          { name: "Inside Sales" },
          { name: "Field Sales" },
          { name: "Key Account Management" },
          { name: "Sales Operations" },
          { name: "Public Relations" },
          { name: "Event Marketing" },
          { name: "Trade Marketing" },
          { name: "Retail Marketing" },
        ],
      },
      {
        name: "Finance & Investment",
        segments: [
          { name: "Investment Banking" },
          { name: "Corporate Finance" },
          { name: "Financial Analysis" },
          { name: "Portfolio Management" },
          { name: "Wealth Management" },
          { name: "Risk Management" },
          { name: "Insurance" },
          { name: "Stock Trading" },
          { name: "Forex Trading" },
          { name: "Commodity Trading" },
          { name: "Mutual Funds" },
          { name: "Hedge Funds" },
          { name: "Private Equity" },
          { name: "Venture Capital" },
          { name: "Angel Investing" },
          { name: "Real Estate Investment" },
          { name: "Cryptocurrency" },
          { name: "DeFi (Decentralized Finance)" },
          { name: "Financial Planning" },
          { name: "Tax Planning" },
          { name: "Retirement Planning" },
          { name: "Estate Planning" },
          { name: "Credit Analysis" },
          { name: "Banking Operations" },
          { name: "Microfinance" },
        ],
      },
      {
        name: "Human Resources",
        segments: [
          { name: "Talent Acquisition" },
          { name: "Recruitment" },
          { name: "Employee Relations" },
          { name: "Performance Management" },
          { name: "Learning & Development" },
          { name: "Compensation & Benefits" },
          { name: "HR Analytics" },
          { name: "Organizational Development" },
          { name: "Change Management" },
          { name: "Diversity & Inclusion" },
          { name: "Employee Engagement" },
          { name: "HR Information Systems (HRIS)" },
          { name: "Labor Relations" },
          { name: "HR Compliance" },
          { name: "Workforce Planning" },
          { name: "Succession Planning" },
          { name: "Executive Coaching" },
          { name: "HR Consulting" },
          { name: "Payroll Management" },
          { name: "Employee Wellness" },
        ],
      },
      {
        name: "Entrepreneurship",
        segments: [
          { name: "Startup Development" },
          { name: "Business Model Innovation" },
          { name: "Product Development" },
          { name: "MVP Development" },
          { name: "Lean Startup" },
          { name: "Growth Hacking" },
          { name: "Fundraising" },
          { name: "Pitch Development" },
          { name: "Angel Investing" },
          { name: "Venture Capital" },
          { name: "Incubation & Acceleration" },
          { name: "Social Entrepreneurship" },
          { name: "Tech Entrepreneurship" },
          { name: "Franchise Business" },
          { name: "Family Business" },
          { name: "Small Business Management" },
          { name: "Business Plan Writing" },
          { name: "Market Validation" },
          { name: "Scaling Operations" },
          { name: "Exit Strategies" },
        ],
      },
      {
        name: "E-commerce & Digital Business",
        segments: [
          { name: "E-commerce Management" },
          { name: "Amazon FBA" },
          { name: "Dropshipping" },
          { name: "Online Marketplace Management" },
          { name: "Digital Product Development" },
          { name: "SaaS Business" },
          { name: "Subscription Business Models" },
          { name: "Online Course Creation" },
          { name: "Digital Marketing Agency" },
          { name: "Affiliate Marketing" },
          { name: "Influencer Business" },
          { name: "Content Creation Business" },
          { name: "YouTube Monetization" },
          { name: "Podcast Monetization" },
          { name: "Social Media Management" },
          { name: "Freelancing Business" },
          { name: "Consulting Business" },
          { name: "Online Coaching" },
          { name: "Digital Nomad Business" },
          { name: "App Monetization" },
        ],
      },
    ],
  },

  // ======================
  // CREATIVE ARTS & DESIGN
  // ======================
  {
    name: "Creative Arts & Design",
    subcategories: [
      {
        name: "Visual Arts & Design",
        segments: [
          { name: "Graphic Design" },
          { name: "UI/UX Design" },
          { name: "Web Design" },
          { name: "Logo Design" },
          { name: "Brand Identity Design" },
          { name: "Print Design" },
          { name: "Packaging Design" },
          { name: "Illustration" },
          { name: "Digital Art" },
          { name: "Concept Art" },
          { name: "Character Design" },
          { name: "Environmental Design" },
          { name: "Typography" },
          { name: "Infographic Design" },
          { name: "Icon Design" },
          { name: "Motion Graphics" },
          { name: "3D Modeling" },
          { name: "3D Animation" },
          { name: "Visual Effects (VFX)" },
          { name: "Game Art" },
          { name: "Comic Art" },
          { name: "Book Cover Design" },
          { name: "Poster Design" },
          { name: "Advertising Design" },
          { name: "Exhibition Design" },
        ],
      },
      {
        name: "Traditional Arts",
        segments: [
          { name: "Painting (Oil, Acrylic, Watercolor)" },
          { name: "Drawing" },
          { name: "Sketching" },
          { name: "Sculpture" },
          { name: "Ceramics & Pottery" },
          { name: "Printmaking" },
          { name: "Calligraphy" },
          { name: "Miniature Painting" },
          { name: "Mural Art" },
          { name: "Street Art" },
          { name: "Installation Art" },
          { name: "Mixed Media Art" },
          { name: "Folk Art" },
          { name: "Tribal Art" },
          { name: "Religious Art" },
          { name: "Portrait Art" },
          { name: "Landscape Art" },
          { name: "Still Life" },
          { name: "Abstract Art" },
          { name: "Contemporary Art" },
        ],
      },
      {
        name: "Photography & Videography",
        segments: [
          { name: "Portrait Photography" },
          { name: "Wedding Photography" },
          { name: "Fashion Photography" },
          { name: "Product Photography" },
          { name: "Food Photography" },
          { name: "Travel Photography" },
          { name: "Wildlife Photography" },
          { name: "Landscape Photography" },
          { name: "Street Photography" },
          { name: "Documentary Photography" },
          { name: "Commercial Photography" },
          { name: "Event Photography" },
          { name: "Sports Photography" },
          { name: "Architectural Photography" },
          { name: "Macro Photography" },
          { name: "Aerial Photography/Drone" },
          { name: "Film Photography" },
          { name: "Photo Editing" },
          { name: "Video Production" },
          { name: "Cinematography" },
          { name: "Video Editing" },
          { name: "Music Video Production" },
          { name: "Commercial Video" },
          { name: "Documentary Filmmaking" },
          { name: "YouTube Content Creation" },
        ],
      },
      {
        name: "Performing Arts",
        segments: [
          { name: "Classical Music" },
          { name: "Western Music" },
          { name: "Folk Music" },
          { name: "Pop Music" },
          { name: "Rock Music" },
          { name: "Jazz" },
          { name: "Blues" },
          { name: "Electronic Music" },
          { name: "Music Production" },
          { name: "Sound Engineering" },
          { name: "Music Composition" },
          { name: "Singing/Vocals" },
          { name: "Instrument Playing" },
          { name: "Music Theory" },
          { name: "Classical Dance (Bharatanatyam, Kathak, etc.)" },
          { name: "Contemporary Dance" },
          { name: "Hip-Hop Dance" },
          { name: "Ballroom Dance" },
          { name: "Folk Dance" },
          { name: "Choreography" },
          { name: "Theatre Acting" },
          { name: "Film Acting" },
          { name: "Voice Acting" },
          { name: "Stand-up Comedy" },
          { name: "Improv Comedy" },
          { name: "Mimicry" },
          { name: "Puppetry" },
          { name: "Magic & Illusion" },
          { name: "Circus Arts" },
          { name: "Storytelling" },
        ],
      },
      {
        name: "Fashion & Styling",
        segments: [
          { name: "Fashion Design" },
          { name: "Textile Design" },
          { name: "Costume Design" },
          { name: "Accessory Design" },
          { name: "Jewelry Design" },
          { name: "Footwear Design" },
          { name: "Handbag Design" },
          { name: "Fashion Styling" },
          { name: "Personal Styling" },
          { name: "Wardrobe Consulting" },
          { name: "Fashion Photography" },
          { name: "Fashion Journalism" },
          { name: "Fashion Marketing" },
          { name: "Fashion Merchandising" },
          { name: "Fashion Forecasting" },
          { name: "Sustainable Fashion" },
          { name: "Fashion Illustration" },
          { name: "Pattern Making" },
          { name: "Garment Construction" },
          { name: "Fashion Technology" },
          { name: "Fashion Retail" },
          { name: "Fashion Event Management" },
          { name: "Fashion Blogging" },
          { name: "Fashion Consultancy" },
          { name: "Color Analysis" },
        ],
      },
      {
        name: "Writing & Literature",
        segments: [
          { name: "Creative Writing" },
          { name: "Novel Writing" },
          { name: "Short Story Writing" },
          { name: "Poetry" },
          { name: "Screenplay Writing" },
          { name: "Playwriting" },
          { name: "Content Writing" },
          { name: "Copywriting" },
          { name: "Technical Writing" },
          { name: "Academic Writing" },
          { name: "Journalism" },
          { name: "Blog Writing" },
          { name: "Grant Writing" },
          { name: "Resume Writing" },
          { name: "Speech Writing" },
          { name: "Translation" },
          { name: "Editing & Proofreading" },
          { name: "Literary Criticism" },
          { name: "Publishing" },
          { name: "Self-Publishing" },
          { name: "E-book Writing" },
          { name: "Children's Book Writing" },
          { name: "Travel Writing" },
          { name: "Food Writing" },
          { name: "Science Writing" },
        ],
      },
      {
        name: "Digital Media & Animation",
        segments: [
          { name: "2D Animation" },
          { name: "3D Animation" },
          { name: "Character Animation" },
          { name: "Motion Graphics" },
          { name: "Visual Effects (VFX)" },
          { name: "Game Animation" },
          { name: "Stop Motion Animation" },
          { name: "Explainer Videos" },
          { name: "Whiteboard Animation" },
          { name: "After Effects" },
          { name: "Cinema 4D" },
          { name: "Maya" },
          { name: "Blender" },
          { name: "Unity" },
          { name: "Unreal Engine" },
          { name: "Digital Compositing" },
          { name: "Rotoscoping" },
          { name: "Match Moving" },
          { name: "Color Grading" },
          { name: "Sound Design" },
        ],
      },
    ],
  },

  // ======================
  // LIFESTYLE & PERSONAL DEVELOPMENT
  // ======================
  {
    name: "Lifestyle & Personal Development",
    subcategories: [
      {
        name: "Self-Improvement",
        segments: [
          { name: "Personal Development" },
          { name: "Life Coaching" },
          { name: "Goal Setting" },
          { name: "Time Management" },
          { name: "Productivity" },
          { name: "Habit Formation" },
          { name: "Mindfulness" },
          { name: "Meditation" },
          { name: "Stress Management" },
          { name: "Emotional Intelligence" },
          { name: "Communication Skills" },
          { name: "Public Speaking" },
          { name: "Presentation Skills" },
          { name: "Leadership Development" },
          { name: "Team Building" },
          { name: "Negotiation Skills" },
          { name: "Conflict Resolution" },
          { name: "Critical Thinking" },
          { name: "Problem Solving" },
          { name: "Decision Making" },
          { name: "Creativity Enhancement" },
          { name: "Memory Improvement" },
          { name: "Speed Reading" },
          { name: "Learning Techniques" },
          { name: "Self-Confidence Building" },
          { name: "Assertiveness Training" },
          { name: "Personal Branding" },
          { name: "Networking Skills" },
          { name: "Social Skills Development" },
          { name: "Body Language" },
          { name: "Charisma Development" },
          { name: "Influence & Persuasion" },
        ],
      },
      {
        name: "Health & Wellness",
        segments: [
          { name: "Nutrition & Diet Planning" },
          { name: "Weight Management" },
          { name: "Mental Health Awareness" },
          { name: "Anxiety Management" },
          { name: "Depression Support" },
          { name: "Therapy & Counseling" },
          { name: "Addiction Recovery" },
          { name: "Sleep Optimization" },
          { name: "Stress Reduction" },
          { name: "Work-Life Balance" },
          { name: "Holistic Health" },
          { name: "Alternative Medicine" },
          { name: "Herbal Medicine" },
          { name: "Aromatherapy" },
          { name: "Acupuncture" },
          { name: "Massage Therapy" },
          { name: "Energy Healing" },
          { name: "Spiritual Healing" },
          { name: "Detoxification" },
          { name: "Anti-Aging" },
          { name: "Longevity" },
          { name: "Preventive Healthcare" },
          { name: "Health Coaching" },
          { name: "Wellness Consulting" },
          { name: "Biohacking" },
        ],
      },
      {
        name: "Relationships & Social Life",
        segments: [
          { name: "Dating & Relationships" },
          { name: "Marriage Counseling" },
          { name: "Family Therapy" },
          { name: "Parenting Skills" },
          { name: "Child Development" },
          { name: "Teen Counseling" },
          { name: "Senior Care" },
          { name: "Social Skills" },
          { name: "Friendship Building" },
          { name: "Community Building" },
          { name: "Social Activism" },
          { name: "Volunteering" },
          { name: "Cultural Integration" },
          { name: "Cross-Cultural Communication" },
          { name: "Language Learning" },
          { name: "International Etiquette" },
          { name: "Event Planning" },
          { name: "Party Planning" },
          { name: "Wedding Planning" },
          { name: "Social Media Management" },
          { name: "Online Dating" },
          { name: "Personal Relationships" },
          { name: "Professional Relationships" },
          { name: "Mentoring" },
          { name: "Coaching Others" },
        ],
      },
      {
        name: "Travel & Adventure",
        segments: [
          { name: "Solo Travel" },
          { name: "Backpacking" },
          { name: "Luxury Travel" },
          { name: "Budget Travel" },
          { name: "Adventure Travel" },
          { name: "Cultural Tourism" },
          { name: "Eco-Tourism" },
          { name: "Wildlife Tourism" },
          { name: "Medical Tourism" },
          { name: "Spiritual Tourism" },
          { name: "Culinary Tourism" },
          { name: "Photography Tours" },
          { name: "Road Trips" },
          { name: "RV Travel" },
          { name: "Cruise Travel" },
          { name: "Train Travel" },
          { name: "Air Travel" },
          { name: "Travel Planning" },
          { name: "Travel Blogging" },
          { name: "Travel Photography" },
          { name: "Travel Writing" },
          { name: "Travel Consulting" },
          { name: "Tour Guiding" },
          { name: "Hospitality" },
          { name: "Travel Insurance" },
          { name: "Visa Consulting" },
          { name: "Expatriate Living" },
          { name: "Digital Nomad Lifestyle" },
          { name: "Remote Work Travel" },
          { name: "House Sitting" },
        ],
      },
      {
        name: "Culinary Arts & Food",
        segments: [
          { name: "Cooking" },
          { name: "Baking" },
          { name: "Pastry Arts" },
          { name: "Cake Decorating" },
          { name: "Chocolate Making" },
          { name: "Wine Making" },
          { name: "Beer Brewing" },
          { name: "Mixology" },
          { name: "Coffee Roasting" },
          { name: "Tea Blending" },
          { name: "Food Styling" },
          { name: "Food Photography" },
          { name: "Food Writing" },
          { name: "Food Blogging" },
          { name: "Restaurant Management" },
          { name: "Catering" },
          { name: "Personal Chef Services" },
          { name: "Meal Planning" },
          { name: "Nutrition Counseling" },
          { name: "Special Diet Cooking" },
          { name: "Vegan Cooking" },
          { name: "Gluten-Free Cooking" },
          { name: "Keto Cooking" },
          { name: "International Cuisine" },
          { name: "Regional Cooking" },
          { name: "Street Food" },
          { name: "Farm-to-Table" },
          { name: "Organic Cooking" },
          { name: "Food Preservation" },
          { name: "Culinary Education" },
        ],
      },
      {
        name: "Hobbies & Crafts",
        segments: [
          { name: "Gardening" },
          { name: "Urban Gardening" },
          { name: "Hydroponics" },
          { name: "Organic Farming" },
          { name: "Permaculture" },
          { name: "Landscaping" },
          { name: "Plant Care" },
          { name: "Flower Arranging" },
          { name: "Bonsai" },
          { name: "Succulents" },
          { name: "Knitting" },
          { name: "Crocheting" },
          { name: "Sewing" },
          { name: "Quilting" },
          { name: "Embroidery" },
          { name: "Cross Stitch" },
          { name: "Scrapbooking" },
          { name: "Card Making" },
          { name: "Jewelry Making" },
          { name: "Beadwork" },
          { name: "Woodworking" },
          { name: "Furniture Making" },
          { name: "Carpentry" },
          { name: "Metalworking" },
          { name: "Pottery" },
          { name: "Ceramics" },
          { name: "Soap Making" },
          { name: "Candle Making" },
          { name: "Leatherworking" },
          { name: "Bookbinding" },
          { name: "Model Making" },
          { name: "Miniatures" },
          { name: "Origami" },
          { name: "Paper Crafts" },
          { name: "Calligraphy" },
          { name: "Coin Collecting" },
          { name: "Stamp Collecting" },
          { name: "Antique Collecting" },
          { name: "Art Collecting" },
          { name: "Book Collecting" },
        ],
      },
      {
        name: "Spirituality & Philosophy",
        segments: [
          { name: "Meditation Practices" },
          { name: "Yoga Philosophy" },
          { name: "Buddhism" },
          { name: "Hinduism" },
          { name: "Christianity" },
          { name: "Islam" },
          { name: "Judaism" },
          { name: "Sikhism" },
          { name: "Jainism" },
          { name: "Taoism" },
          { name: "Zen Philosophy" },
          { name: "Sufism" },
          { name: "Mysticism" },
          { name: "Spirituality" },
          { name: "Astrology" },
          { name: "Numerology" },
          { name: "Tarot Reading" },
          { name: "Crystal Healing" },
          { name: "Chakra Healing" },
          { name: "Reiki" },
          { name: "Feng Shui" },
          { name: "Vastu Shastra" },
          { name: "Dream Interpretation" },
          { name: "Past Life Regression" },
          { name: "Spiritual Counseling" },
          { name: "Life Purpose Discovery" },
          { name: "Consciousness Studies" },
          { name: "Philosophy" },
          { name: "Ethics" },
          { name: "Logic" },
        ],
      },
    ],
  },

  // ======================
  // SPORTS & FITNESS
  // ======================
  {
    name: "Sports & Fitness",
    subcategories: [
      {
        name: "Fitness & Exercise",
        segments: [
          { name: "Personal Training" },
          { name: "Strength Training" },
          { name: "Weight Training" },
          { name: "Bodybuilding" },
          { name: "Powerlifting" },
          { name: "Olympic Lifting" },
          { name: "CrossFit" },
          { name: "HIIT (High-Intensity Interval Training)" },
          { name: "Circuit Training" },
          { name: "Functional Training" },
          { name: "Calisthenics" },
          { name: "Cardio Training" },
          { name: "Running" },
          { name: "Jogging" },
          { name: "Marathon Training" },
          { name: "Sprinting" },
          { name: "Cycling" },
          { name: "Mountain Biking" },
          { name: "Road Cycling" },
          { name: "Swimming" },
          { name: "Water Aerobics" },
          { name: "Diving" },
          { name: "Triathlon" },
          { name: "Decathlon" },
          { name: "Track & Field" },
        ],
      },
      {
        name: "Yoga & Mind-Body Practices",
        segments: [
          { name: "Hatha Yoga" },
          { name: "Vinyasa Yoga" },
          { name: "Ashtanga Yoga" },
          { name: "Bikram Yoga" },
          { name: "Hot Yoga" },
          { name: "Yin Yoga" },
          { name: "Restorative Yoga" },
          { name: "Power Yoga" },
          { name: "Kundalini Yoga" },
          { name: "Prenatal Yoga" },
          { name: "Yoga Therapy" },
          { name: "Meditation" },
          { name: "Pilates" },
          { name: "Barre" },
          { name: "Tai Chi" },
          { name: "Qigong" },
          { name: "Alexander Technique" },
          { name: "Feldenkrais Method" },
          { name: "Somatic Movement" },
          { name: "Dance Therapy" },
        ],
      },
      {
        name: "Team Sports",
        segments: [
          { name: "Football (Soccer)" },
          { name: "Cricket" },
          { name: "Basketball" },
          { name: "Volleyball" },
          { name: "Hockey (Field)" },
          { name: "Ice Hockey" },
          { name: "Baseball" },
          { name: "Softball" },
          { name: "Rugby" },
          { name: "American Football" },
          { name: "Handball" },
          { name: "Water Polo" },
          { name: "Kabaddi" },
          { name: "Kho Kho" },
          { name: "Ultimate Frisbee" },
          { name: "Lacrosse" },
          { name: "Netball" },
          { name: "Sepak Takraw" },
          { name: "Team Coaching" },
          { name: "Sports Psychology" },
        ],
      },
      {
        name: "Individual Sports",
        segments: [
          { name: "Tennis" },
          { name: "Badminton" },
          { name: "Table Tennis" },
          { name: "Squash" },
          { name: "Golf" },
          { name: "Athletics" },
          { name: "Gymnastics" },
          { name: "Wrestling" },
          { name: "Boxing" },
          { name: "Martial Arts" },
          { name: "Karate" },
          { name: "Taekwondo" },
          { name: "Judo" },
          { name: "Jiu-Jitsu" },
          { name: "Muay Thai" },
          { name: "Kickboxing" },
          { name: "Mixed Martial Arts (MMA)" },
          { name: "Fencing" },
          { name: "Archery" },
          { name: "Shooting" },
          { name: "Bowling" },
          { name: "Billiards/Pool" },
          { name: "Snooker" },
          { name: "Darts" },
          { name: "Chess" },
        ],
      },
      {
        name: "Adventure & Outdoor Sports",
        segments: [
          { name: "Rock Climbing" },
          { name: "Mountain Climbing" },
          { name: "Mountaineering" },
          { name: "Trekking" },
          { name: "Hiking" },
          { name: "Backpacking" },
          { name: "Camping" },
          { name: "Survival Skills" },
          { name: "Orienteering" },
          { name: "Geocaching" },
          { name: "White Water Rafting" },
          { name: "Kayaking" },
          { name: "Canoeing" },
          { name: "Sailing" },
          { name: "Windsurfing" },
          { name: "Kitesurfing" },
          { name: "Surfing" },
          { name: "Scuba Diving" },
          { name: "Free Diving" },
          { name: "Snorkeling" },
          { name: "Paragliding" },
          { name: "Hang Gliding" },
          { name: "Skydiving" },
          { name: "Bungee Jumping" },
          { name: "BASE Jumping" },
          { name: "Skiing" },
          { name: "Snowboarding" },
          { name: "Ice Climbing" },
          { name: "Sledding" },
          { name: "ATV Riding" },
        ],
      },
      {
        name: "Sports Science & Management",
        segments: [
          { name: "Sports Medicine" },
          { name: "Exercise Physiology" },
          { name: "Sports Nutrition" },
          { name: "Sports Psychology" },
          { name: "Biomechanics" },
          { name: "Kinesiology" },
          { name: "Athletic Training" },
          { name: "Sports Injury Rehabilitation" },
          { name: "Sports Therapy" },
          { name: "Sports Massage" },
          { name: "Fitness Assessment" },
          { name: "Performance Analysis" },
          { name: "Sports Coaching" },
          { name: "Sports Management" },
          { name: "Sports Marketing" },
          { name: "Sports Journalism" },
          { name: "Sports Broadcasting" },
          { name: "Sports Photography" },
          { name: "Sports Event Management" },
          { name: "Referee/Umpiring" },
        ],
      },
    ],
  },

  // ======================
  // MEDIA & ENTERTAINMENT
  // ======================
  {
    name: "Media & Entertainment",
    subcategories: [
      {
        name: "Film & Television",
        segments: [
          { name: "Film Direction" },
          { name: "Cinematography" },
          { name: "Film Production" },
          { name: "Screenwriting" },
          { name: "Film Editing" },
          { name: "Sound Design" },
          { name: "Music Composition for Film" },
          { name: "Production Design" },
          { name: "Costume Design" },
          { name: "Makeup & Prosthetics" },
          { name: "Visual Effects (VFX)" },
          { name: "Special Effects" },
          { name: "Stunt Coordination" },
          { name: "Casting" },
          { name: "Talent Management" },
          { name: "Film Distribution" },
          { name: "Film Marketing" },
          { name: "Documentary Filmmaking" },
          { name: "Short Films" },
          { name: "Web Series" },
          { name: "Television Production" },
          { name: "Reality TV Production" },
          { name: "News Production" },
          { name: "Sports Broadcasting" },
          { name: "Live Streaming" },
        ],
      },
      {
        name: "Digital Content Creation",
        segments: [
          { name: "YouTube Content Creation" },
          { name: "TikTok Content" },
          { name: "Instagram Content" },
          { name: "Podcast Production" },
          { name: "Audio Content Creation" },
          { name: "Blog Content" },
          { name: "Vlog Creation" },
          { name: "Social Media Content" },
          { name: "Influencer Marketing" },
          { name: "Brand Collaboration" },
          { name: "Affiliate Marketing" },
          { name: "Content Strategy" },
          { name: "Community Management" },
          { name: "Live Streaming" },
          { name: "Gaming Content" },
          { name: "Educational Content" },
          { name: "Entertainment Content" },
          { name: "Tutorial Content" },
          { name: "Review Content" },
          { name: "Unboxing Videos" },
          { name: "Reaction Videos" },
          { name: "Travel Content" },
          { name: "Food Content" },
          { name: "Fashion Content" },
          { name: "Tech Reviews" },
        ],
      },
      {
        name: "Gaming & Esports",
        segments: [
          { name: "Professional Gaming" },
          { name: "Esports" },
          { name: "Game Streaming" },
          { name: "Game Development" },
          { name: "Game Design" },
          { name: "Level Design" },
          { name: "Game Art" },
          { name: "Game Animation" },
          { name: "Game Programming" },
          { name: "Game Testing" },
          { name: "Game Writing" },
          { name: "Game Audio" },
          { name: "Mobile Game Development" },
          { name: "Indie Game Development" },
          { name: "VR Game Development" },
          { name: "AR Game Development" },
          { name: "Game Marketing" },
          { name: "Game Journalism" },
          { name: "Gaming Commentary" },
          { name: "Esports Coaching" },
          { name: "Esports Management" },
          { name: "Gaming Hardware Reviews" },
          { name: "Speedrunning" },
          { name: "Game Modding" },
          { name: "Gaming Community Building" },
        ],
      },
      {
        name: "Radio & Audio",
        segments: [
          { name: "Radio Broadcasting" },
          { name: "Radio Programming" },
          { name: "Radio Jockeying (RJ)" },
          { name: "Podcast Hosting" },
          { name: "Audio Production" },
          { name: "Sound Engineering" },
          { name: "Music Production" },
          { name: "Audio Editing" },
          { name: "Voiceover" },
          { name: "Dubbing" },
          { name: "Audio Book Narration" },
          { name: "Radio Drama" },
          { name: "Commercial Production" },
          { name: "Jingle Creation" },
          { name: "Audio Journalism" },
          { name: "Live Audio Mixing" },
          { name: "Studio Management" },
          { name: "Radio Marketing" },
          { name: "Community Radio" },
          { name: "Internet Radio" },
        ],
      },
      {
        name: "Publishing & Print Media",
        segments: [
          { name: "Book Publishing" },
          { name: "Magazine Publishing" },
          { name: "Newspaper Publishing" },
          { name: "Digital Publishing" },
          { name: "Self-Publishing" },
          { name: "E-book Publishing" },
          { name: "Academic Publishing" },
          { name: "Children's Book Publishing" },
          { name: "Comic Book Publishing" },
          { name: "Literary Agenting" },
          { name: "Editorial Services" },
          { name: "Copyediting" },
          { name: "Proofreading" },
          { name: "Book Design" },
          { name: "Cover Design" },
          { name: "Typography" },
          { name: "Print Production" },
          { name: "Distribution" },
          { name: "Book Marketing" },
          { name: "Literary Criticism" },
          { name: "Book Reviewing" },
          { name: "Literary Events" },
          { name: "Reading Programs" },
          { name: "Library Sciences" },
          { name: "Archives Management" },
        ],
      },
    ],
  },

  // ======================
  // SERVICE INDUSTRIES
  // ======================
  {
    name: "Service Industries",
    subcategories: [
      {
        name: "Hospitality & Tourism",
        segments: [
          { name: "Hotel Management" },
          { name: "Restaurant Management" },
          { name: "Food & Beverage Service" },
          { name: "Front Office Operations" },
          { name: "Housekeeping Management" },
          { name: "Event Management" },
          { name: "Wedding Planning" },
          { name: "Conference Management" },
          { name: "Travel & Tourism" },
          { name: "Tour Operations" },
          { name: "Travel Agency" },
          { name: "Cruise Operations" },
          { name: "Resort Management" },
          { name: "Spa Management" },
          { name: "Recreation Management" },
          { name: "Customer Service" },
          { name: "Hospitality Marketing" },
          { name: "Revenue Management" },
          { name: "Sustainable Tourism" },
          { name: "Cultural Tourism" },
          { name: "Adventure Tourism" },
          { name: "Medical Tourism" },
          { name: "Eco-Tourism" },
          { name: "Heritage Tourism" },
          { name: "Rural Tourism" },
        ],
      },
      {
        name: "Beauty & Wellness",
        segments: [
          { name: "Cosmetology" },
          { name: "Hair Styling" },
          { name: "Hair Coloring" },
          { name: "Makeup Artistry" },
          { name: "Skincare Specialist" },
          { name: "Esthetics" },
          { name: "Nail Technology" },
          { name: "Spa Therapy" },
          { name: "Massage Therapy" },
          { name: "Aromatherapy" },
          { name: "Reflexology" },
          { name: "Beauty Consulting" },
          { name: "Bridal Makeup" },
          { name: "Special Effects Makeup" },
          { name: "Permanent Makeup" },
          { name: "Eyebrow Styling" },
          { name: "Eyelash Extensions" },
          { name: "Beauty Photography" },
          { name: "Beauty Blogging" },
          { name: "Product Development" },
          { name: "Beauty Sales" },
          { name: "Salon Management" },
          { name: "Beauty Education" },
          { name: "Wellness Coaching" },
          { name: "Holistic Beauty" },
        ],
      },
      {
        name: "Personal Services",
        segments: [
          { name: "Personal Training" },
          { name: "Life Coaching" },
          { name: "Career Coaching" },
          { name: "Relationship Coaching" },
          { name: "Health Coaching" },
          { name: "Fitness Coaching" },
          { name: "Nutrition Coaching" },
          { name: "Personal Shopping" },
          { name: "Image Consulting" },
          { name: "Wardrobe Styling" },
          { name: "Color Analysis" },
          { name: "Personal Assistant" },
          { name: "Virtual Assistant" },
          { name: "Concierge Services" },
          { name: "Pet Care" },
          { name: "Pet Grooming" },
          { name: "Pet Training" },
          { name: "House Sitting" },
          { name: "Cleaning Services" },
          { name: "Organizing Services" },
          { name: "Interior Decorating" },
          { name: "Home Staging" },
          { name: "Gardening Services" },
          { name: "Handyman Services" },
          { name: "Moving Services" },
        ],
      },
      {
        name: "Transportation & Logistics",
        segments: [
          { name: "Logistics Management" },
          { name: "Supply Chain Management" },
          { name: "Warehouse Management" },
          { name: "Inventory Management" },
          { name: "Transportation Management" },
          { name: "Fleet Management" },
          { name: "Freight Forwarding" },
          { name: "Customs Clearance" },
          { name: "Import/Export" },
          { name: "Distribution" },
          { name: "Last Mile Delivery" },
          { name: "E-commerce Fulfillment" },
          { name: "Cold Chain Management" },
          { name: "Reverse Logistics" },
          { name: "Procurement" },
          { name: "Vendor Management" },
          { name: "Quality Control" },
          { name: "Compliance Management" },
          { name: "Risk Management" },
          { name: "Sustainability in Logistics" },
          { name: "Driver Services" },
          { name: "Ride Sharing" },
          { name: "Delivery Services" },
          { name: "Courier Services" },
          { name: "Moving & Relocation" },
        ],
      },
      {
        name: "Professional Services",
        segments: [
          { name: "Consulting" },
          { name: "Management Consulting" },
          { name: "Strategy Consulting" },
          { name: "IT Consulting" },
          { name: "Financial Consulting" },
          { name: "HR Consulting" },
          { name: "Marketing Consulting" },
          { name: "Legal Consulting" },
          { name: "Tax Consulting" },
          { name: "Audit Services" },
          { name: "Accounting Services" },
          { name: "Bookkeeping" },
          { name: "Payroll Services" },
          { name: "Business Registration" },
          { name: "Compliance Services" },
          { name: "Document Services" },
          { name: "Translation Services" },
          { name: "Interpretation Services" },
          { name: "Notary Services" },
          { name: "Insurance Services" },
          { name: "Real Estate Services" },
          { name: "Property Management" },
          { name: "Investment Advisory" },
          { name: "Wealth Management" },
          { name: "Financial Planning" },
        ],
      },
    ],
  },

  // ======================
  // MANUFACTURING & TRADES
  // ======================
  {
    name: "Manufacturing & Trades",
    subcategories: [
      {
        name: "Skilled Trades",
        segments: [
          { name: "Carpentry" },
          { name: "Plumbing" },
          { name: "Electrical Work" },
          { name: "HVAC (Heating, Ventilation, Air Conditioning)" },
          { name: "Masonry" },
          { name: "Roofing" },
          { name: "Painting & Decorating" },
          { name: "Tiling" },
          { name: "Flooring Installation" },
          { name: "Drywall Installation" },
          { name: "Insulation Installation" },
          { name: "Window Installation" },
          { name: "Door Installation" },
          { name: "Fencing" },
          { name: "Landscaping" },
          { name: "Welding" },
          { name: "Metalworking" },
          { name: "Machining" },
          { name: "Auto Mechanics" },
          { name: "Motorcycle Mechanics" },
          { name: "Heavy Equipment Operation" },
          { name: "Crane Operation" },
          { name: "Forklift Operation" },
          { name: "Construction Management" },
          { name: "Project Management" },
        ],
      },
      {
        name: "Manufacturing",
        segments: [
          { name: "Production Management" },
          { name: "Quality Control" },
          { name: "Quality Assurance" },
          { name: "Process Engineering" },
          { name: "Industrial Engineering" },
          { name: "Manufacturing Engineering" },
          { name: "Lean Manufacturing" },
          { name: "Six Sigma" },
          { name: "Automation" },
          { name: "Robotics" },
          { name: "CNC Machining" },
          { name: "3D Printing" },
          { name: "Injection Molding" },
          { name: "Die Casting" },
          { name: "Stamping" },
          { name: "Forging" },
          { name: "Assembly Line Work" },
          { name: "Packaging" },
          { name: "Inventory Control" },
          { name: "Materials Management" },
          { name: "Supply Chain Coordination" },
          { name: "Safety Management" },
          { name: "Environmental Compliance" },
          { name: "Maintenance Management" },
          { name: "Equipment Management" },
        ],
      },
      {
        name: "Artisan & Craft Trades",
        segments: [
          { name: "Jewelry Making" },
          { name: "Pottery & Ceramics" },
          { name: "Glassblowing" },
          { name: "Leatherworking" },
          { name: "Bookbinding" },
          { name: "Furniture Making" },
          { name: "Cabinet Making" },
          { name: "Woodturning" },
          { name: "Blacksmithing" },
          { name: "Silversmithing" },
          { name: "Watch Making" },
          { name: "Instrument Making" },
          { name: "Shoe Making" },
          { name: "Tailoring" },
          { name: "Embroidery" },
          { name: "Weaving" },
          { name: "Basket Making" },
          { name: "Candle Making" },
          { name: "Soap Making" },
          { name: "Perfume Making" },
          { name: "Food Artisan" },
          { name: "Brewing" },
          { name: "Distilling" },
          { name: "Cheese Making" },
          { name: "Artisan Bakery" },
        ],
      },
    ],
  },

  // ======================
  // GOVERNMENT & PUBLIC SERVICE
  // ======================
{
  name: "Government & Public Service",
  subcategories: [
    {
      name: "Public Administration",
      segments: [
        { name: "Policy Development" },
        { name: "Public Sector Management" },
        { name: "Government Operations" },
        { name: "Public Budgeting" },
        { name: "Legislative Services" },
        { name: "Regulatory Affairs" },
      ],
    },
    {
      name: "Law Enforcement & Security",
      segments: [
        { name: "Police Services" },
        { name: "Criminal Investigation" },
        { name: "Border Security" },
        { name: "Correctional Services" },
        { name: "Cybersecurity" },
        { name: "Intelligence Analysis" },
      ],
    },
    {
      name: "Emergency Services",
      segments: [
        { name: "Firefighting" },
        { name: "Emergency Medical Services" },
        { name: "Disaster Response" },
        { name: "Search & Rescue" },
        { name: "Hazardous Materials Handling" },
      ],
    },
    {
      name: "Diplomacy & International Relations",
      segments: [
        { name: "Foreign Service" },
        { name: "International Negotiation" },
        { name: "Trade Representation" },
        { name: "Cultural Diplomacy" },
        { name: "Development Aid" },
      ],
    },
    {
      name: "Community & Social Services",
      segments: [
        { name: "Public Health Education" },
        { name: "Welfare Services" },
        { name: "Youth Services" },
        { name: "Elderly Care Programs" },
        { name: "Nonprofit Management" },
      ],
    },
  ],
}